jsonrpc:
    discovery:
        zookeeper: localhost:2181
    client:
        serverList: localhost:12306
        connectionTimeoutMS: 5000
        invokeTimeoutMS: 1000
spring:
    devtools:
        livereload:
            enabled: true
            port: 35728
    restart:
        enabled: true
server:
    port: 9090